version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: nextjs-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - KEYCLOAK_CLIENT_ID=nextjs-client
      - KEYCLOAK_CLIENT_SECRET=OPec83kvvJGeXdMzSywGGTlRohVOtxee
      - KEYCLOAK_ISSUER=http://q-caas-wk-02.sec.telecel.net.py:8080/realms/MFS_ACCESS_INVOICES
      - KEYCLOAK_URL=http://q-caas-wk-02.sec.telecel.net.py:8080
      - KEYCLOAK_AUTH=http://q-caas-wk-02.sec.telecel.net.py:8080/realms/MFS_ACCESS_INVOICES/protocol/openid-connect/ext/ciba/auth
      - KEYCLOAK_REALM=MFS_ACCESS_INVOICES
      - NEXT_PUBLIC_URL_BACKEND=http://mfs-invoice-web-api.qa.sec.telecel.net.py/invoices
      - NEXT_PUBLIC_URL_BACKEND_STATS=http://mfs-invoice-web-api.qa.sec.telecel.net.py/invoices/stats
      - NEXT_PUBLIC_URL_BACKEND_ANALYTICS=http://mfs-invoice-web-api.qa.sec.telecel.net.py/invoices/analytics
      - NEXT_PUBLIC_MAX_FILE_SIZE=10737418240
      - BASE_URL=http://mfs-invoice-web-api.qa.sec.telecel.net.py
      - UPLOAD_DIR=/app/uploads
      - CONCURRENT_WORKERS=4
    volumes:
      # Montar el entrypoint script
      - ./entrypoint.sh:/app/entrypoint.sh
      - nextjs_uploads:/app/uploads
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nextjs-network
    driver: bridge

volumes:
  nextjs_uploads:
